api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    #Home
    path('', views.api, name='api'),
    path('get_topics/', views.get_topic, name='get_topic'),
    path('add_topic/', views.add_topic, name='add_topic'),        
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [  
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import TopicSerializer

from blogapp.models import Topic

def api(request):
  return render(request, 'api/api.html')

@api_view(['GET'])
def get_topic(request):
  topics = Topic.objects.all()
  serializer = TopicSerializer(topics, many=True)
  return Response(serializer.data)

@api_view(['POST'])
def add_topic(request):
  serializer = TopicSerializer(data=request.data)
  if serializer.is_valid():
    serializer.save()
  return Response(serializer.data)

api/templates/api/api.html
{% extends 'blogapp/base_container.html' %}
{% load static %}
{% block content %}

<header class="p-3 border-bottom mb-5">
  <a href="/" class="d-flex align-items-center  text-dark text-decoration-none">
    <i class="fa-solid fa-circle-nodes fa-2xl "></i>
    <span class="fs-4 ms-3">Rest API</span>
  </a>
</header>



  <a class ="" href="{% url 'api:get_topic' %}">Get</a>
  <br><br>

  <a class ="" href="{% url 'api:add_topic' %}">Add</a>
  

{% endblock content %}